export interface Question {
  id: number;
  text: string;
}

export const QUESTIONS: Question[] = [
  { id: 1, text: "I usually finish important tasks even when they become repetitive." },
  { id: 2, text: "I find it easy to start conversations with people I don't know." },
  { id: 3, text: "Under pressure, I can usually keep my thoughts organised." },
  { id: 4, text: "I enjoy learning about subjects even when they have no immediate use." },
  { id: 5, text: "I generally try to understand another person's position before responding." },
  { id: 6, text: "Achieving difficult goals is personally satisfying to me." },
  { id: 7, text: "When my first attempt fails, I usually try another approach." },
  { id: 8, text: "If I notice something that needs doing, I often start without waiting to be asked." },
  { id: 9, text: "I sometimes leave important tasks unfinished once the interesting part is over." },
  { id: 10, text: "I am comfortable expressing my opinion even when others may disagree." },
  { id: 11, text: "Small setbacks can affect my mood for quite a while." },
  { id: 12, text: "I enjoy reconsidering assumptions that most people take for granted." },
  { id: 13, text: "I sometimes avoid disagreement even when I think something important needs to be said." },
  { id: 14, text: "I set demanding standards for what I want to accomplish." },
  { id: 15, text: "Repeated rejection makes it difficult for me to maintain the same level of effort." },
  { id: 16, text: "I prefer receiving detailed instructions before beginning unfamiliar work." },
  { id: 17, text: "I can make myself work on something even when I don't feel particularly motivated." },
  { id: 18, text: "In a group, I am comfortable being the person who starts the discussion." },
  { id: 19, text: "I generally remain composed when several things go wrong at once." },
  { id: 20, text: "I prefer familiar approaches to experimenting with new ways of doing things." },
  { id: 21, text: "I find it easy to work with people whose personalities are very different from mine." },
  { id: 22, text: "I am satisfied doing enough to meet expectations rather than trying to exceed them." },
  { id: 23, text: "I can continue pursuing an objective after several unsuccessful attempts." },
  { id: 24, text: "When faced with an unclear problem, I usually begin figuring it out rather than waiting for someone else." },
  { id: 25, text: "I plan my work so that important things are unlikely to be forgotten." },
  { id: 26, text: "I sometimes hold back from speaking even when I have something useful to contribute." },
  { id: 27, text: "When someone reacts negatively toward me, I can usually move on quickly." },
  { id: 28, text: "I like situations that require me to learn something completely new." },
  { id: 29, text: "I try to be considerate even when I am trying to get something I want." },
  { id: 30, text: "I enjoy having a clear goal that allows me to measure how well I am performing." },
  { id: 31, text: "If something isn't working after a few attempts, I tend to lose interest." },
  { id: 32, text: "I regularly look for useful things I can do beyond what has specifically been assigned to me." },
  { id: 33, text: "Deadlines help me focus, but I rarely need them to make myself get things done." },
  { id: 34, text: "I enjoy situations where I need to persuade someone to consider my point of view." },
  { id: 35, text: "Uncertainty tends to make me worry about what could go wrong." },
  { id: 36, text: "When I encounter an unfamiliar idea, I want to understand how it works." },
  { id: 37, text: "Being liked is usually more important to me than winning an argument." },
  { id: 38, text: "I am strongly motivated by seeing myself improve at something." },
  { id: 39, text: "A \"no\" usually makes me want to understand whether another route might work." },
  { id: 40, text: "When I see an opportunity, I am comfortable acting before I have every detail." },
  { id: 41, text: "I sometimes put off straightforward tasks longer than I should." },
  { id: 42, text: "I am comfortable asking someone directly for a decision." },
  { id: 43, text: "I can perform effectively even when I feel under pressure." },
  { id: 44, text: "I enjoy solving problems where the answer isn't immediately obvious." },
  { id: 45, text: "I can be very direct when I think directness is necessary." },
  { id: 46, text: "I rarely compare my current performance with what I could potentially achieve." },
  { id: 47, text: "Slow progress does not usually stop me from working toward something I consider important." },
  { id: 48, text: "I tend to wait for someone else to take charge when a situation is ambiguous." },
  { id: 49, text: "Once I make a commitment, people can generally rely on me to follow through." },
  { id: 50, text: "Meeting new people usually gives me energy." },
  { id: 51, text: "Criticism can stay on my mind for a long time." },
  { id: 52, text: "I enjoy discovering better ways of doing things I already know how to do." },
  { id: 53, text: "I can disagree with someone while still maintaining a productive relationship with them." },
  { id: 54, text: "I like having ambitious targets even when I might not achieve all of them." },
  { id: 55, text: "When I encounter resistance, I usually become curious about what is causing it." },
  { id: 56, text: "I am comfortable making reasonable decisions without first getting approval for every step." },
  { id: 57, text: "I am careful about details that could affect the quality of my work." },
  { id: 58, text: "I find sustained interaction with unfamiliar people draining." },
  { id: 59, text: "Unexpected problems rarely prevent me from concentrating on what needs to happen next." },
  { id: 60, text: "I am interested in understanding why people or organisations behave the way they do." },
  { id: 61, text: "I sometimes soften what I really think to avoid creating tension." },
  { id: 62, text: "Once I reach an acceptable level of performance, I usually don't feel much need to improve further." },
  { id: 63, text: "I can maintain effort even when I receive very little encouragement." },
  { id: 64, text: "I often identify the next thing that needs doing before someone tells me." },
  { id: 65, text: "My work habits are fairly consistent from one day to another." },
  { id: 66, text: "I am comfortable taking the lead in conversations with people more senior than me." },
  { id: 67, text: "I become flustered more easily than most people when plans suddenly change." },
  { id: 68, text: "I like examining a problem from several different perspectives." },
  { id: 69, text: "I generally give people the benefit of the doubt." },
  { id: 70, text: "Difficult targets tend to increase my motivation." },
  { id: 71, text: "After an unsuccessful outcome, I can usually reset quickly and try again." },
  { id: 72, text: "If I don't know how to do something, my first instinct is usually to try to figure out what I can before asking someone to solve it for me." },
];

export const LIKERT_SCALE = [
  { value: 1, label: "Strongly disagree" },
  { value: 2, label: "Disagree" },
  { value: 3, label: "Neither agree nor disagree" },
  { value: 4, label: "Agree" },
  { value: 5, label: "Strongly agree" },
];
